### Call API
GET http://localhost:8080/

### Authenticate
## Generated base64 encoded string for "user:pwd" "ermal:ermal" in https://www.base64encode.org/
POST http://localhost:8080/token
Authorization: Basic ZXJtYWw6ZXJtYWw=

### Call API with Generated Token
GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZXJtYWwiLCJleHAiOjE2NjY1NDA1NzQsImlhdCI6MTY2NjUzNjk3NCwic2NvcGUiOiJyZWFkIn0.ZJJsU2se7Qn6e5iCa44L6-mRUCWPeQyjI8ad1r6AJLoCZYo10i71TXRblLLRidqkGr2oP3tlLhZPPMMdDktJf6ruMr7bRJ0a54qzu6e4frzEguRMx86khSpzWOoWskaOvMfyWsuc7mhxClHSC1iKniOZmM7xsXI2lIvcHhRv1xv_xmu0iZHNaHfv0VZ3_iCEK4KRWG08pcGiIID_NiIVOHDrJfto5rpRhKxMjDGENaBI6vgb90rdD3BVi8LqvqXAYYvPHRsONJtGz_qBvpbCd6rQUdVSpz6Nd3m_dna9YjOV8s5QuJ3PR6mwVsLSeCf6MU7O_8Ofm_DhYoUg-bAEjTLR_wFDqEMJumoNKofklaVOmNsZsRkSn2WBdlT8_Lv031CRuvO1dY3f1xQBhIm66mCoQv0zb2teD7QXEvH1n14KGoovPdKM6bt0ro3g6lj_bmQtNf0fdHXcTxWvJVuElsN3DZc

### Call API with Basci Token  (this shouldn't work ?)
GET http://localhost:8080/
Authorization: Basic ZXJtYWw6ZXJtYWw=

###